name: Bitcoin Improvement Proposal Gallery
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title/
url: https://bips.gallery/
author:
    name: Prayank
    twitter: https://twitter.com/prayankgahlot
